### ISSUE TITLE
Bot start error

### ISSUE THREAD

**Issue by krushna06** [DeltaCoderr/KarmaBot#40]
Whenever I try to start the bot it gives me the error saying ``` node karma.js
/home/runner/KarmaBot/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/KarmaBot/node_modules/discord-player/src/Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/KarmaBot/node_modules/discord-player/index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
exit status 1```

**Comment by DeltaCoderr** [comment]
Upgrade your Node version to x14.

**Comment by DeltaCoderr** [comment]
That should solve it.
