### ISSUE TITLE
Module discord.js error

### ISSUE THREAD

**Issue by Axtazer** [DeltaCoderr/KarmaBot#42]
###  Error module discord.js

Info : 

Node version :  v15.13.0
npm version : 7.7.6

Logs : 
 
user@00.00.00.00: /home/debian/Bots/BotPrincipal/KarmaBot# node karma.js
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/debian/Bots/BotPrincipal/KarmaBot/karma.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/debian/Bots/BotPrincipal/KarmaBot/karma.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/debian/Bots/BotPrincipal/KarmaBot/karma.js' ]
}

To install modules : 

user@00.00.00.00: /home/debian/Bots/BotPrincipal/KarmaBot# npm i
npm ERR! code 1
npm ERR! path /home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.13.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/root/.cache/node-gyp/15.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/15.13.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/15.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: gyp failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.0-16-cloud-amd64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v15.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by Axtazer** [comment]
And for the `npm i` 

KarmaBot# npm i
npm ERR! code 1
npm ERR! path /home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.13.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/15.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.0-16-cloud-amd64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/debian/Bots/BotPrincipal/KarmaBot/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/debian/Bots/BotPrincipal/KarmaBot/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v15.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
