### ISSUE TITLE
im getting mongodb error on replit , anyone can help me ?

### ISSUE THREAD

**Issue by Mohammadjoon1453** [DeltaCoderr/KarmaBot#55]
hey guys
i have a problem :(( 
when i use chatbot 
and type &setchatbotchannel #txt-channel-id
bot respond to me : ChatBot Channel has been Set Successfully

and then im just speaking to bot
but But bot does not answer me
and i see error in console repl :
`(node:46) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at request (https.js:313:10)
    at /home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1407:9)
    at Client.<anonymous> (/home/runner/KarmaBot/index.js:62:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:46) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:46) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at request (https.js:313:10)
    at /home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1407:9)
    at Client.<anonymous> (/home/runner/KarmaBot/index.js:62:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:46) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at request (https.js:313:10)
    at /home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/home/runner/KarmaBot/node_modules/node-fetch/lib/index.js:1407:9)
    at Client.<anonymous> (/home/runner/KarmaBot/index.js:62:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`

what should i do now ?

**Comment by DeltaCoderr** [comment]
[This should help](https://stackoverflow.com/questions/54025710/typeerror-err-unescaped-characters-request-path-contains-unescaped-characters)
